# -*- coding: utf-8 -*-
"""Scraping Data from a Real Website.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhvdA6x76VPInBjSOZng34Wcoi9r2127

# **Scraping Data from a Real Website + Pandas**
"""

import requests
from bs4 import BeautifulSoup

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

print(soup)

soup.find('table')

soup.find_all('table')[1]

soup.find('table', class_ = 'wikitable sortable')

table = soup.find_all('table')[1]
print(table)

world_titles = table.find_all('th')

print(world_titles)

world_table_titles = [title.text.strip() for title in world_titles]

print(world_table_titles)

import pandas as pd

df = pd.DataFrame(columns = world_table_titles)

df

column_data = table.find_all('tr')

print(column_data)

for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

df

df.to_csv("List of the largest companies by revenue in 2023.cvs")

